config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  root to: 'users#index'


  resources :pictures do
    collection do
    post :confirm
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { in: 1..140 }
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :user_login_check, only: [:new]

  def index
    @pictures = Picture.all
  end

  def show
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def edit
  end
  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to @picture, notice: 'Picture was posted'
      else
        render :new
      end
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end
  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was updated' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html {redirect_to pictures_url, notice: 'Picture was deleted'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end
    def picture_params
      params.require(:picture).permit(:content, :image, :image_cache)
    end

    def user_login_check
   unless logged_in?
     redirect_to root_path
   end
 end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'Login failed'
      render :new
  end
  end
  def destroy
     session.delete(:user_id)
     flash[:notice] = 'Logged out'
     redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :login_required, only: [:new, :create]
  def show
       @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
      redirect_to user_path(@user.id)
      else
        render :new
      end
  end
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)

    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>FacebkClone</title>
    <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<ul class="menu">
  <li>
  <a href="#home">Home</a>
  </li>
  <li>
  <a href="/pictures">show</a>
  </li>
  <li>
  <a href="#">Profile</a>
  </li>
  <li>
  <a href="">Log In</a>
  </li>
  <li>
  <a href="#new_user_path">Sign Up</a>
  </li>
</ul>

<body>
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <% if logged_in? %>
  <%= link_to "Profile", user_path(current_user.id) %>
  <%= link_to "Log Out", session_path(current_user.id), method: :delete %>
  <% else %>
  <%= link_to "Sign Up", new_user_path %>
  <%= link_to "Log In", new_session_path %>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true ,url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h1>Do you want to post this ?</h1>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <!-- Description for displaying the uploaded image on the confirmation screen -->
  <%= form.hidden_field :content %>
  <p>Content: <%= @picture.content %></p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Post" %>
  <% end %>
  <%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Do not post", name: 'Back' %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td>
        <% if picture.image_url %>
          <%= image_tag picture.image_url, style:'width:60%;height:40%' %>
       <% end %>

  </td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<p id="notice"><%= notice %></p>
<%= render 'form', picture: @picture %><br>
<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
<%= image_tag @picture.image.url %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <ul class="btn-group btn-group-sm">
                <li class="col-md-12"><h3>Username: <%= user.name %></h3></li>
                <li class="col-md-12"><h3>Email: <%= user.email %></h3></li>
              </ul>
                <button type="button" class="btn btn-info"><%= link_to 'See', user, data: { confirm: 'Are you sure?' } %></button>
                <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_user_path(user), data: { confirm: 'Are you sure?' } %></button>
                <button type="button" class="btn btn-danger"><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></button>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
 <% if @user.errors.any? %>
 <div id="error_explanation">
 <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
 <ul>
 <% @user.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
 </ul>
 </div>
 <% end %>

 <%= form_with(model: @user, local: true) do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.label :email %>
 <%= f.email_field :email %>
 <%= f.label :password %>
 <%= f.password_field :password %>
 <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation %>
 <%= f.submit "Create my account" %>
 <% end %>

app/views/users/show.html.erb
<h1> Welcome to <%= @user.name %>'s page</h1>
<p>Email address: <%= @user.email %></p>

<%= link_to 'New Picture', new_picture_path %>